name: food_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.15.0

  firebase_core: ^0.6.0
  firebase_auth: ^0.19.0+1
  auto_size_text: ^2.1.0
  auth_buttons: ^0.0.4
  google_sign_in: ^4.5.9
#  date_range_picker: ^1.0.6
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  google_fonts: ^1.1.2
  sqflite: ^1.3.0
  path: ^1.8.0
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.1
  flutter_svg: ^0.22.0
  percent_indicator: ^3.0.1

  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  datetime_picker_formfield: ^1.0.0
  get: ^3.26.0
  pie_chart: ^4.0.1
  flutter_datetime_picker: ^1.5.0
  syncfusion_flutter_charts: ^18.4.49
  syncfusion_flutter_core: ^18.4.49
  shared_preferences: ^0.5.12+4
  timeline_tile: ^1.0.0
  flutter_showcase: ^0.1.0
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  date_range_picker:
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/order_confirmed.png
    - assets/icons/order_placed.png
    - assets/icons/order_processed.png
    - assets/icons/ready_to_pickup.png
